### PR TITLE
Better error message for state persisting

### LINKED ISSUE #202: Make save state error message more descriptive
### Steps to reproduce

- Go to the project root
- `$ mkdir state.json`
- Run dimooper
- Press `S`

### Observed

```
[ERROR] Is a directory (os error 21)
```

### Expected

A more descriptive error message, because from the currrent one it is not clear what happened.

### PR DESCRIPTION
**Pull request by rexim**
Close #202

### CODE REVIEW

File: src/path.rs [hunk 1]
```diff
@@ -0,0 +1,11 @@
+use std;
+use std::path::{Path, PathBuf};
+
+/// Converts Path into absolute PathBuf. Should be used only for
+/// display in messages since it suppresses any errors and falls back
```
Comment (rexim) [inline src/path.rs]: *for displaying

File: src/screen/looper_screen.rs [hunk 2]
```diff
@@ -53,16 +55,24 @@ impl<NoteTracker: MidiNoteTracker> Screen<()> for LooperScreen<NoteTracker> {
...
-                    match self.looper.load_state_from_file(Path::new(STATE_FILE_PATH)) {
-                        Ok(_) => println!("Loaded looper state from {}", STATE_FILE_PATH),
-                        Err(e) => println!("[ERROR] {}", e),
+                    let state_file_path = Path::new(STATE_FILE_PATH);
+                    let absolute_path = path::display_absolute_path(state_file_path);
+                    match self.looper.load_state_from_file(state_file_path) {
+                        Ok(_) => println!("Loaded looper state from {}", absolute_path.display()),
+                        Err(e) => println!("[ERROR] Could not load state from {}. Reason: {}",
+                                           absolute_path.display(),
+                                           e),
```
Comment (rexim) [inline src/screen/looper_screen.rs]: Extend `be91501b-fd60-450d-b5c7-5ee4ad261c0c` to get rid of duplicate code
